# EC2 -> Spring 배포용
name: spring-deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # PR이 닫혔을 때만 실행됨 (merge 포함)
    paths-ignore:
      - 'src/main/frontend/**' # 해당 경로(REACT) 제외

jobs:
  Spring-Deploy:
    if: github.event.pull_request.merged == true  # '닫힘' 중에서도 실제로 merge된 경우에만 실행
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{secrets.APPLICATION_YML}}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credential@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{secrets.SPRING_AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.SPRING_AWS_SECRET_ACCESS_KEY}}

      - name: ECR에 로그인하기 # ECR에 로그인하는 라이브러리 사용.
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성 # .표시는 현재 경로 Dockerfile 기반으로 이미지를 생성한다는 의미
        run: docker build -t hamtalk-server .

      - name: Docker 이미지에 Tag 붙이기 # 도커 이미지 주소값
        run: docker tag hamtalk-server ${{steps.login-ecr.outputs.registry}}/hamtalk-server:latest

      - name: ECR에 Docker 이미지 Push
        run: docker push ${{steps.login-ecr.outputs.registry}}/hamtalk-server:latest

      - name: 압축하기
        run: tar -czvf $GITHUB_SHA.tar.gz appspec.yml scripts

      - name: S3에 프로젝트 폴더 업로드하기
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://hamtalk-server/$GITHUB_SHA.tar.gz

      - name: Code Deploy를 활용해 EC2에 프로젝트 코드 배포
        run: aws deploy create-deployment
          --application-name hamtalk-server
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name Production
          --s3-location bucket=hamtalk-server,bundleType=tgz,key=$GITHUB_SHA.tar.gz